// default-data.js

const DEFAULT_EXERCISES = [
    // Push
    { name: 'Bench Press (Barbell)', category: 'Push' },
    { name: 'Bench Press (Dumbbell)', category: 'Push' },
    { name: 'Overhead Press (Barbell)', category: 'Push' },
    { name: 'Overhead Press (Dumbbell)', category: 'Push' },
    { name: 'Incline Bench Press (Barbell)', category: 'Push' },
    { name: 'Incline Bench Press (Dumbbell)', category: 'Push' },
    { name: 'Chest Press (Machine)', category: 'Push' },
    { name: 'Shoulder Press (Machine)', category: 'Push' },
    { name: 'Dips', category: 'Push' },
    { name: 'Push-ups', category: 'Push' },
    { name: 'Lateral Raise (Dumbbell)', category: 'Push' },
    { name: 'Lateral Raise (Cable)', category: 'Push' },
    { name: 'Lateral Raise (Machine)', category: 'Push' },
    { name: 'Tricep Pushdown (Cable)', category: 'Push' },
    { name: 'Tricep Extension (Dumbbell)', category: 'Push' },
    { name: 'Skull Crusher', category: 'Push' },
    { name: 'Pec Deck / Chest Fly (Machine)', category: 'Push' },
    { name: 'Cable Crossover', category: 'Push' },

    // Pull
    { name: 'Pull-ups', category: 'Pull' },
    { name: 'Chin-ups', category: 'Pull' },
    { name: 'Lat Pulldown', category: 'Pull' },
    { name: 'Barbell Row', category: 'Pull' },
    { name: 'Pendlay Row', category: 'Pull' },
    { name: 'Dumbbell Row', category: 'Pull' },
    { name: 'Seated Cable Row', category: 'Pull' },
    { name: 'T-Bar Row', category: 'Pull' },
    { name: 'Row (Machine)', category: 'Pull' },
    { name: 'Bicep Curl (Barbell)', category: 'Pull' },
    { name: 'Bicep Curl (Dumbbell)', category: 'Pull' },
    { name: 'Hammer Curl', category: 'Pull' },
    { name: 'Preacher Curl', category: 'Pull' },
    { name: 'Face Pull', category: 'Pull' },
    { name: 'Rear Delt Fly (Machine)', category: 'Pull' },
    { name: 'Shrugs (Barbell)', category: 'Pull' },
    { name: 'Shrugs (Dumbbell)', category: 'Pull' },
    
    // Legs
    { name: 'Squat (Barbell)', category: 'Legs' },
    { name: 'Front Squat (Barbell)', category: 'Legs' },
    { name: 'Deadlift (Conventional)', category: 'Legs' },
    { name: 'Deadlift (Sumo)', category: 'Legs' },
    { name: 'Romanian Deadlift (Barbell)', category: 'Legs' },
    { name: 'Romanian Deadlift (Dumbbell)', category: 'Legs' },
    { name: 'Leg Press', category: 'Legs' },
    { name: 'Lunge (Dumbbell)', category: 'Legs' },
    { name: 'Lunge (Barbell)', category: 'Legs' },
    { name: 'Hack Squat', category: 'Legs' },
    { name: 'Leg Extension (Machine)', category: 'Legs' },
    { name: 'Leg Curl (Machine)', category: 'Legs' },
    { name: 'Hip Thrust (Barbell)', category: 'Legs' },
    { name: 'Calf Raise (Machine)', category: 'Legs' },
    { name: 'Calf Raise (Dumbbell)', category: 'Legs' },
    { name: 'Goblet Squat', category: 'Legs' },
    { name: 'Adductor Machine', category: 'Legs' },
    { name: 'Abductor Machine', category: 'Legs' },

    // Other (Core/Cardio)
    { name: 'Plank', category: 'Other' },
    { name: 'Crunches', category: 'Other' },
    { name: 'Hanging Leg Raise', category: 'Other' },
    { name: 'Cable Woodchopper', category: 'Other' },
    { name: 'Russian Twist', category: 'Other' },
    { name: 'Treadmill', category: 'Other' },
    { name: 'Elliptical', category: 'Other' },
    { name: 'Stationary Bike', category: 'Other' }
];
